import type { ChapterDefinition, SceneDefinition } from "../../types/game";

export const openingChapter: ChapterDefinition = {
  id: "shadows-beneath-mistvale",
  name: "הצללים שמתחת לערפלון",
  estimatedMinutes: [70, 120],
  openingNarration: [
    "אלף שנים חלפו מאז התאחדו שבעה שליטים נגד המלך שמעבר לערפל.",
    "הם לא הצליחו להרוג אותו. במקום זאת חישלו את כתר הברית וכבלו אותו בין העולמות.",
    "הטקס שבר את הכתר לשבעה רסיסים. כל רסיס הוסתר, והאמת נשחקה לאגדה.",
    "עכשיו מכרות נפתחים מעצמם, גבישים שחורים צומחים בחורבות, ואנשים זרים חולמים את אותו חלום.",
    "אל הכפר המרוחק ערפלון מגיע נוסע אלמוני, רגע לאחר שהאדמה מפסיקה לרעוד.",
  ],
  sceneIds: [
    "scene-arrival",
    "scene-village-leader",
    "scene-preparation",
    "scene-road-to-mine",
    "scene-mine-entrance",
    "scene-tutorial-combat",
    "scene-main-tunnel",
    "scene-trapped-miner",
    "scene-cult-evidence",
    "scene-hidden-area",
    "scene-stone-guardian",
    "scene-crown-shard",
    "scene-chapter-completion",
  ],
  mainQuestId: "shadows-beneath-village",
  finalReward: { experience: 420, gold: 65, itemIds: ["first-crown-shard", "guardian-core"], reputation: 8 },
  nextChapterHook: "הרונה שעל הרסיס מצביעה צפונה, אל הדרך שנעלמה מתחת לערפל ואל עיר שאינה מופיעה עוד בשום מפה.",
};

export const openingScenes: SceneDefinition[] = [
  {
    id: "scene-arrival",
    number: 1,
    title: "הגעה לערפלון",
    locationId: "village-gate",
    description: "היכרות עם הכפר הפגוע, האבק הכחול והסימנים הראשונים לכך שהרעידה לא הייתה טבעית.",
    entryNarration: "גלגלי העגלה נעצרים מול שער סדוק. אף ציפור אינה שרה, אך פעמון הכפר מצלצל פעם אחת מעצמו.",
    interactionIds: ["inspect-blue-dust", "study-earthquake-cracks"],
    requiredFlags: [],
    completionConditions: [{ kind: "flag", key: "arrived_in_arfelon", value: true }],
    nextSceneIds: ["scene-village-leader"],
    skippableCinematic: true,
  },
  {
    id: "scene-village-leader",
    number: 2,
    title: "ראש הכפר",
    locationId: "headman-house",
    description: "אלריק מציג את היעלמות הכורים, והדמות יכולה לדרוש אמת, לגלות את סוד משפחתו או לנהל משא ומתן.",
    entryNarration: "אלריק סוגר את הדלת על רעש הכיכר. המפתח שעל צווארו פולט חום כחול מבעד לחולצה.",
    interactionIds: ["speak-elric-private", "inspect-old-map"],
    requiredFlags: ["met_elric"],
    completionConditions: [{ kind: "flag", key: "quest_accepted", value: true }],
    nextSceneIds: ["scene-preparation"],
  },
  {
    id: "scene-preparation",
    number: 3,
    title: "הכנות בכפר",
    locationId: "arfelon-square",
    description: "ביקורים אופציונליים אצל מירה, תאל וברום מעניקים ציוד, רמזים, יחסים ומשימה צדדית.",
    entryNarration: "לפני העלייה למכרה נותר זמן קצר. שלושה מקומות בכפר עדיין מוארים: הנפחייה, בקתת המרפא והפונדק.",
    interactionIds: ["speak-mira", "speak-thal", "speak-brom", "search-locked-room"],
    requiredFlags: ["quest_accepted"],
    completionConditions: [{ kind: "flag", key: "ready_to_leave_village", value: true }],
    nextSceneIds: ["scene-road-to-mine"],
  },
  {
    id: "scene-road-to-mine",
    number: 4,
    title: "הדרך הנעלמת",
    locationId: "mine-road",
    description: "בדיקת הישרדות או תפיסה חושפת עקבות אנשי כת ומונעת מארב; כישלון יוצר עימות חלופי.",
    entryNarration: "העצים נסגרים סביב הדרך. ארבעה זוגות עקבות מופיעים בבוץ באמצע השביל, כאילו בעליהם נפלו מן השמים.",
    interactionIds: ["track-hooded-figures", "grey-woman-glimpse", "disable-cult-beacon", "read-watchtower-orders", "search-watch-post", "restore-waystone-oath", "use-elric-seal-at-waystones", "listen-to-waystone"],
    requiredFlags: ["ready_to_leave_village"],
    completionConditions: [{ kind: "flag", key: "road_resolved", value: true }],
    nextSceneIds: ["scene-mine-entrance"],
  },
  {
    id: "scene-mine-entrance",
    number: 5,
    title: "הפתח שנפרץ מבפנים",
    locationId: "mine-entrance",
    description: "דם, כלים שבורים וסמל הכת יוצרים חקירה קצרה עם תוצאות שונות לפני העימות הראשון.",
    entryNarration: "ריח ברזל רטוב עולה מן המכרה. חריטת עין שבורה נראית חדשה, אך הפיח שבתוכה קר בן מאות שנים.",
    interactionIds: ["inspect-blood-tools", "inspect-cult-symbol"],
    requiredFlags: ["road_resolved"],
    completionConditions: [{ kind: "flag", key: "mine_entrance_investigated", value: true }],
    nextSceneIds: ["scene-tutorial-combat"],
  },
  {
    id: "scene-tutorial-combat",
    number: 6,
    title: "היצור שבחושך",
    locationId: "mine-entrance",
    description: "קרב הדרכה נגד עכברוש מערות מושחת מלמד יכולות, משאבים, התגוננות וחפצים.",
    entryNarration: "העגלה ההפוכה זזה. מתחתיה נפקחות שתי עיניים שחורות, וגבישים מתחילים להאיר מתחת לפרווה.",
    interactionIds: ["tutorial-combat"],
    requiredFlags: ["mine_entrance_investigated"],
    completionConditions: [{ kind: "flag", key: "tutorial_enemy_defeated", value: true }],
    nextSceneIds: ["scene-main-tunnel"],
  },
  {
    id: "scene-main-tunnel",
    number: 7,
    title: "הקול מעבר למפולת",
    locationId: "main-tunnel",
    description: "החבורה שומעת את דנור וצריכה לבחור בין חילוץ מיידי, חיפוש נתיב בטוח או המשך מסוכן.",
    entryNarration: "שלוש נקישות נשמעות מן הקיר. אחרי הפסקה ארוכה מגיע קול: ‘אם מישהו שם—אל תיגעו בגבישים.’",
    interactionIds: ["listen-danor", "find-secret-draft"],
    requiredFlags: ["tutorial_enemy_defeated"],
    completionConditions: [{ kind: "flag", key: "heard_danor", value: true }],
    nextSceneIds: ["scene-trapped-miner"],
  },
  {
    id: "scene-trapped-miner",
    number: 8,
    title: "הכורה הלכוד",
    locationId: "abandoned-tool-store",
    description: "חילוץ דנור אפשרי בכוח, רפואה, חבל או נתיב חלופי; אפשר גם להשאירו, וההחלטה נשמרת.",
    entryNarration: "דנור שוכב מתחת לקורה. הוא מנסה לחייך, אך האצבעות סביב המדליון השחור לבנות ממאמץ.",
    interactionIds: ["speak-danor", "recover-foreman-journal", "find-rune-hammer"],
    requiredFlags: ["heard_danor"],
    completionConditions: [{ kind: "flag", key: "danor_resolved", value: true }],
    nextSceneIds: ["scene-cult-evidence"],
  },
  {
    id: "scene-cult-evidence",
    number: 9,
    title: "עקבות העין השבורה",
    locationId: "pillar-hall",
    description: "שרידי טקס, כתב שרוף, גביש שחור ועקבות מוכיחים שאנשי הכת הגיעו ראשונים ופתחו את ההיכל.",
    entryNarration: "העקבות מסתיימות במעגל שעווה. במרכזו מוטבעה כף יד בעלת שש אצבעות, ואף אדם לא יצא מן המעגל.",
    interactionIds: ["study-cult-remains", "open-hidden-door"],
    requiredFlags: ["danor_resolved"],
    completionConditions: [{ kind: "flag", key: "cult_opened_guardian_hall", value: true }],
    nextSceneIds: ["scene-hidden-area", "scene-stone-guardian"],
  },
  {
    id: "scene-hidden-area",
    number: 10,
    title: "מפת שבעת השברים",
    locationId: "hidden-chamber",
    description: "אזור אופציונלי ובו ציוד נדיר, לור על שבעת הרסיסים ויתרון ממשי נגד השומר.",
    entryNarration: "הקיר נפתח ללא אבק. שבעה נתיבי נחושת זורחים ברצפה, וכל אחד מהם מסתיים במקום אחר בעולם.",
    interactionIds: ["decode-seven-regions", "open-ancient-chest"],
    requiredFlags: ["hidden_chamber_open"],
    completionConditions: [{ kind: "flag", key: "hidden_area_resolved", value: true }],
    nextSceneIds: ["scene-stone-guardian"],
  },
  {
    id: "scene-stone-guardian",
    number: 11,
    title: "שומר האבן העתיק",
    locationId: "guardian-sanctum",
    description: "קרב בוס טקטי עם משמר שביר, רונה חשופה, מכה כבדה מסומנת מראש והתאמה לגודל החבורה.",
    entryNarration: "הרונה בחזה הפסל נדלקת. קול אבן אומר: ‘הברית נשברה. אין מורשים.’ השרשראות מתפקעות.",
    interactionIds: ["inspect-guardian-before-combat", "fight-stone-guardian"],
    requiredFlags: ["cult_opened_guardian_hall"],
    completionConditions: [{ kind: "flag", key: "guardian_defeated", value: true }],
    nextSceneIds: ["scene-crown-shard"],
  },
  {
    id: "scene-crown-shard",
    number: 12,
    title: "רסיס הכתר הראשון",
    locationId: "guardian-sanctum",
    description: "הרסיס מעניק חיזיון של שבעת השליטים, הכתר הנשבר, הכס השחור והעין שמעבר לערפל.",
    entryNarration: "מאחורי השומר נפתח כן האבן. רסיס דק מרחף מעליו, ושמים אפורים משתקפים במתכת אף שהתקרה שלמה.",
    interactionIds: ["touch-first-shard"],
    requiredFlags: ["guardian_defeated"],
    completionConditions: [{ kind: "flag", key: "vision_seen", value: true }],
    nextSceneIds: ["scene-chapter-completion"],
  },
  {
    id: "scene-chapter-completion",
    number: 13,
    title: "מה שהערפל זוכר",
    locationId: "arfelon-square",
    description: "חזרה פעילה לכפר: תגובות מירה, תאל וברום, גורל דנור והחלטה פומבית מה לחשוף על הרסיס.",
    entryNarration: "כששבים לערפלון, כל הפעמונים מצלצלים יחד. הרסיס פועם פעם אחת, והערפל בצפון נפתח בצורת דרך.",
    interactionIds: ["speak-mira-return", "speak-thal-return", "speak-brom-return", "report-elric-return-rescued", "report-elric-return-abandoned"],
    requiredFlags: ["vision_seen"],
    completionConditions: [{ kind: "flag", key: "chapter_one_completed", value: true }],
    nextSceneIds: [],
  },
];

export const openingScenesById = Object.fromEntries(openingScenes.map((scene) => [scene.id, scene])) as Record<string, SceneDefinition>;

export const chapterSummaryFields = [
  { id: "miners", label: "כורים שניצלו", flag: "danor_rescued" },
  { id: "cult", label: "זהות הפולשים", flag: "cult_evidence_found" },
  { id: "secret", label: "החדר הנסתר", flag: "hidden_chamber_open" },
  { id: "guardian", label: "שומר האבן", flag: "guardian_defeated" },
  { id: "voice", label: "תשובתך לקול", flag: "answered_fog_voice" },
  { id: "waystones", label: "ברית אבני הסף", flag: "waystone_ward_restored" },
  { id: "beacon", label: "אות מגדל הכת", flag: "tower_beacon_disabled" },
  { id: "truth", label: "האמת נחשפה לכפר", flag: "shard_truth_revealed" },
] as const;
