import type { DialogueNode } from "../types/game";

export const dialogues: DialogueNode[] = [
  {
    id: "elric-introduction",
    npcId: "elric",
    portraitKey: "portrait-npc-elric",
    emotionalState: "טרוד אך בשליטה",
    text: "אתה לא מכאן, וזה כרגע יתרון. שלושה מאנשינו נכנסו למכרה אחרי הרעידה. איש מהם לא חזר, והקולות מן הגבעה מתחזקים.",
    onEnterEffects: [{ kind: "set-flag", key: "met_elric", value: true }],
    choices: [
      { id: "elric-kind", text: "אעזור. ספר לי מי הם ומה חיכה להם שם.", approach: "kind", effects: [{ kind: "relationship", npcId: "elric", field: "trust", amount: 4 }], nextNodeId: "elric-quest" },
      { id: "elric-direct", text: "אם אתה רוצה שאכנס לשם, אני צריך את כל האמת.", approach: "direct", effects: [{ kind: "relationship", npcId: "elric", field: "respect", amount: 3 }], nextNodeId: "elric-hidden-truth" },
      { id: "elric-curious", text: "מדוע מכרה נטוש היה פתוח מספיק כדי שכורים ייכנסו אליו?", approach: "curious", nextNodeId: "elric-hidden-truth" },
      { id: "elric-soldier", text: "[חייל לשעבר] לפני משימה מסוכנת מציגים מפה, סיכון ונתיב נסיגה.", approach: "background-specific", conditions: [{ kind: "background", backgroundId: "former-soldier" }], effects: [{ kind: "relationship", npcId: "elric", field: "respect", amount: 6 }, { kind: "set-flag", key: "elric_shared_map", value: true }], nextNodeId: "elric-quest" },
      { id: "elric-noble", text: "[בן אצולה שנפל] כפר שנוטש את אנשיו מאבד את זכותו לבקש נאמנות.", approach: "background-specific", conditions: [{ kind: "background", backgroundId: "fallen-noble" }], effects: [{ kind: "relationship", npcId: "elric", field: "fear", amount: 3 }], nextNodeId: "elric-quest" },
    ],
    oneTime: true,
  },
  {
    id: "elric-hidden-truth",
    npcId: "elric",
    portraitKey: "portrait-npc-elric",
    emotionalState: "מתגונן",
    text: "המכרה נפתח מעצמו. הקורות נבקעו החוצה, כאילו משהו בפנים דחף אותן. הוריתי לאיש לא להתקרב. דנור ושני האחרים חשבו שיוכלו להציל את כלי העבודה.",
    choices: [
      {
        id: "elric-insight", text: "אתה מדקלם את הסיפור. מה השמטת?", approach: "curious",
        skillCheck: {
          skill: "insight", attribute: "wisdom", difficulty: 13, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "elric_knew_old_seal", value: true }, { kind: "relationship", npcId: "elric", field: "trust", amount: 2 }],
          failureEffects: [{ kind: "relationship", npcId: "elric", field: "trust", amount: -3 }],
          criticalSuccessEffects: [{ kind: "set-flag", key: "elric_ancestor_guarded_mine", value: true }],
        },
        nextNodeId: "elric-confession",
      },
      { id: "elric-accept-limits", text: "אתמודד עם מה שאמצא. תן לי את פרטי הדרך.", approach: "direct", nextNodeId: "elric-quest" },
      { id: "elric-threat", text: "אם מישהו ימות בגלל סוד שלך, אחזור לסגור את החשבון.", approach: "threatening", effects: [{ kind: "relationship", npcId: "elric", field: "fear", amount: 8 }, { kind: "relationship", npcId: "elric", field: "trust", amount: -5 }], nextNodeId: "elric-quest" },
    ],
  },
  {
    id: "elric-confession",
    npcId: "elric",
    portraitKey: "portrait-npc-elric",
    emotionalState: "נכנע לזיכרון",
    text: "במשפחתי עובר מפתח שאינו פותח דלת. נאמר לנו לשמור אותו ולהקשיב אם האבן מתחילה לשיר. בלילה שלפני הרעידה המפתח נעשה חם. פחדתי שהכפר ייכנס לפאניקה.",
    choices: [
      { id: "elric-confession-kind", text: "פחד אינו פשע. מה שתעשה עכשיו הוא שיקבע.", approach: "kind", effects: [{ kind: "relationship", npcId: "elric", field: "trust", amount: 7 }, { kind: "set-flag", key: "elric_gave_seal_key", value: true }], nextNodeId: "elric-quest" },
      { id: "elric-confession-direct", text: "הסוד הזה כמעט עלה בשלושה אנשים. מעכשיו אין עוד השמטות.", approach: "direct", effects: [{ kind: "relationship", npcId: "elric", field: "respect", amount: 5 }, { kind: "set-flag", key: "elric_gave_seal_key", value: true }], nextNodeId: "elric-quest" },
    ],
  },
  {
    id: "elric-quest",
    npcId: "elric",
    portraitKey: "portrait-npc-elric",
    emotionalState: "נחוש",
    text: "מצא את הכורים אם עוד אפשר. גלה מי צייר את הסמל השחור בכניסה, וסגור כל דבר שנפתח מתחתינו. מירה, תאל וברום יעזרו לך להתכונן.",
    choices: [
      {
        id: "elric-negotiate", text: "הסיכון גדול. הכפר צריך להתחייב לתשלום הוגן.", approach: "direct",
        skillCheck: {
          skill: "persuasion", attribute: "charisma", difficulty: 12, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "bonus_reward_negotiated", value: true }, { kind: "relationship", npcId: "elric", field: "respect", amount: 2 }],
          failureEffects: [{ kind: "set-flag", key: "standard_reward_only", value: true }],
          criticalSuccessEffects: [{ kind: "set-flag", key: "free_village_services", value: true }],
        },
        effects: [{ kind: "quest-start", questId: "shadows-beneath-village" }, { kind: "set-flag", key: "quest_accepted", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "speak-to-headman", status: "completed" }],
        exitAction: "close",
      },
      { id: "elric-accept", text: "אצא לאחר שאצטייד.", approach: "direct", effects: [{ kind: "quest-start", questId: "shadows-beneath-village" }, { kind: "set-flag", key: "quest_accepted", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "speak-to-headman", status: "completed" }], exitAction: "close" },
      { id: "elric-kind-promise", text: "אחזיר את אנשיך אם נשארה דרך לעשות זאת.", approach: "kind", effects: [{ kind: "relationship", npcId: "elric", field: "trust", amount: 4 }, { kind: "quest-start", questId: "shadows-beneath-village" }, { kind: "set-flag", key: "quest_accepted", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "speak-to-headman", status: "completed" }], exitAction: "close" },
    ],
  },
  {
    id: "mira-earthquake",
    npcId: "mira",
    portraitKey: "portrait-npc-mira",
    emotionalState: "חשדנית",
    text: "אם אלריק שלח אותך, הוא כנראה גם שכח לומר שהמתכת שרה לפני שהאדמה זזה. כל מכוש שהגיע מן המכרה התעקם לאותו כיוון.",
    choices: [
      { id: "mira-ask-tools", text: "המתכת נמשכה אל משהו?", approach: "curious", effects: [{ kind: "set-flag", key: "metal_points_to_shard", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "ask-mira-earthquake", status: "completed" }], nextNodeId: "mira-supplies" },
      { id: "mira-mage", text: "[קוסם] זו תהודה מאגית. משהו מתחת לאבן מפעיל שדה משיכה.", approach: "class-specific", conditions: [{ kind: "class", classId: "mage" }], effects: [{ kind: "relationship", npcId: "mira", field: "respect", amount: 3 }, { kind: "relationship", npcId: "mira", field: "trust", amount: -2 }, { kind: "set-flag", key: "guardian_rune_suspected", value: true }], nextNodeId: "mira-supplies" },
      { id: "mira-dwarf", text: "[גמד] אבן לא מעקמת ברזל בלי להשאיר בו גרגר. זה הגיע מרונה.", approach: "race-specific", conditions: [{ kind: "race", raceId: "dwarf" }], effects: [{ kind: "relationship", npcId: "mira", field: "respect", amount: 6 }, { kind: "set-flag", key: "guardian_rune_understood", value: true }], nextNodeId: "mira-supplies" },
      { id: "mira-joke", text: "אם המכושים בורחים מן המכרה, אולי כדאי להקשיב להם.", approach: "humorous", effects: [{ kind: "relationship", npcId: "mira", field: "trust", amount: 2 }], nextNodeId: "mira-supplies" },
    ],
    oneTime: true,
  },
  {
    id: "mira-supplies",
    npcId: "mira",
    portraitKey: "portrait-npc-mira",
    emotionalState: "עניינית",
    text: "קח מכוש ולפיד. לא, אל תודה לי. תחזיר את דנור, ואז נדבר על תודות. אם תמצא פטיש עם ראש נחושת במחסן הישן, הוא היה של אבי.",
    choices: [
      { id: "mira-take-supplies", text: "אשמור על הכלים ואחפש את הפטיש.", approach: "kind", effects: [{ kind: "grant-item", itemId: "miners-pick", quantity: 1 }, { kind: "grant-item", itemId: "village-torch", quantity: 2 }, { kind: "set-flag", key: "prepared_with_mira", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "obtain-light", status: "completed" }], exitAction: "close" },
      { id: "mira-open-shop", text: "אני צריך לבדוק גם את שאר הציוד.", approach: "direct", effects: [{ kind: "grant-item", itemId: "village-torch", quantity: 1 }, { kind: "set-flag", key: "prepared_with_mira", value: true }], exitAction: "open-shop" },
    ],
  },
  {
    id: "thal-corruption",
    npcId: "thal",
    portraitKey: "portrait-npc-thal",
    emotionalState: "שקט ומודאג",
    text: "הכורים שהיו ליד הפתח השתעלו אבקה שחורה, אף שלא נכנסו פנימה. אם תראה גביש כהה, אל תשבור אותו ואל תיתן לדם לגעת בו.",
    choices: [
      { id: "thal-ask-why", text: "אתה מדבר מניסיון.", approach: "curious", conditions: [{ kind: "flag", key: "thal_exposed_to_corruption", value: true }], effects: [{ kind: "relationship", npcId: "thal", field: "trust", amount: 4 }], nextNodeId: "thal-confession" },
      { id: "thal-medicine", text: "[מיומן ברפואה] הכתם בציפורן שלך מתקדם נגד זרם הדם. מתי נגעת בגביש?", approach: "background-specific", conditions: [{ kind: "background", backgroundId: "temple-servant" }], effects: [{ kind: "relationship", npcId: "thal", field: "trust", amount: 6 }, { kind: "set-flag", key: "thal_treatment_clue", value: true }], nextNodeId: "thal-confession" },
      { id: "thal-accept-warning", text: "אשמור מרחק מן הגבישים. יש לך משהו שיסייע לפצועים?", approach: "direct", nextNodeId: "thal-supplies" },
    ],
    oneTime: true,
  },
  {
    id: "thal-confession",
    npcId: "thal",
    portraitKey: "portrait-npc-thal",
    emotionalState: "חשוף",
    text: "מצאתי שבב בבגד של אחד הפצועים. החזקתי אותו רק רגע ושמעתי קול מבקש שאפתח דלת. מאז כולנו חולמים אותו חלום.",
    choices: [
      { id: "thal-compassion", text: "נמצא דרך לעצור את זה. בינתיים שמור את היד עטופה בכסף.", approach: "kind", effects: [{ kind: "relationship", npcId: "thal", field: "trust", amount: 8 }, { kind: "set-flag", key: "shared_nightmare_confirmed", value: true }], nextNodeId: "thal-supplies" },
      { id: "thal-direct", text: "אם הקול חוזר, אל תענה לו. שלח מישהו לאלריק מיד.", approach: "direct", effects: [{ kind: "relationship", npcId: "thal", field: "respect", amount: 5 }, { kind: "set-flag", key: "shared_nightmare_confirmed", value: true }], nextNodeId: "thal-supplies" },
    ],
  },
  {
    id: "thal-supplies",
    npcId: "thal",
    portraitKey: "portrait-npc-thal",
    emotionalState: "מעודד",
    text: "קח את הבקבוק הזה ומשחה לדנור. השיקוי יסגור פצע; המשחה תקנה לו זמן. אלה אינם אותו דבר.",
    choices: [
      { id: "thal-take-healing", text: "אשתמש בהם בחוכמה.", approach: "kind", effects: [{ kind: "grant-item", itemId: "minor-healing-potion", quantity: 1 }, { kind: "grant-item", itemId: "healers-salve", quantity: 1 }, { kind: "set-flag", key: "prepared_with_thal", value: true }], exitAction: "close" },
    ],
  },
  {
    id: "brom-rumors",
    npcId: "brom",
    portraitKey: "portrait-npc-brom",
    emotionalState: "עליז מדי",
    text: "שלושה כורים, מכרה מקולל, רעידה באמצע הלילה—בימים רגילים הייתי אומר שזו התחלה מצוינת לשיר. היום אני מעדיף סוף משעמם.",
    choices: [
      { id: "brom-ask-strangers", text: "מי הגיע לכפר לפני הרעידה?", approach: "direct", nextNodeId: "brom-strangers" },
      {
        id: "brom-deceive", text: "אלריק כבר סיפר לי על האורחים בגלימות. אני רק בודק אם הסיפור שלך תואם.", approach: "deceptive",
        skillCheck: {
          skill: "deception", attribute: "charisma", difficulty: 12, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "brom_room_key", value: true }, { kind: "relationship", npcId: "brom", field: "fear", amount: 4 }],
          failureEffects: [{ kind: "relationship", npcId: "brom", field: "trust", amount: -4 }],
          criticalSuccessEffects: [{ kind: "set-flag", key: "cult_leader_was_woman", value: true }],
        },
        nextNodeId: "brom-strangers",
      },
      { id: "brom-humor", text: "סוף משעמם עולה תוספת או שהוא כלול במחיר החדר?", approach: "humorous", effects: [{ kind: "relationship", npcId: "brom", field: "trust", amount: 4 }], nextNodeId: "brom-strangers" },
      { id: "brom-criminal", text: "[פושע לשעבר] הסימן מתחת לדלפק אומר שהיה פה אורח ששילם בשתיקה.", approach: "background-specific", conditions: [{ kind: "background", backgroundId: "former-criminal" }], effects: [{ kind: "set-flag", key: "brom_room_key", value: true }, { kind: "relationship", npcId: "brom", field: "respect", amount: 5 }], nextNodeId: "brom-strangers" },
    ],
    oneTime: true,
  },
  {
    id: "brom-strangers",
    npcId: "brom",
    portraitKey: "portrait-npc-brom",
    emotionalState: "נכנע ללחץ",
    text: "ארבעה. גלימות אפורות, אבל לא כמו האישה שמסתובבת ביער. הם לא אכלו, לא ישנו באמת, ובחצות שמעתי אותם חוזרים על המשפט ‘השבר זוכר את היד’.",
    choices: [
      { id: "brom-request-key", text: "תן לי את המפתח לחדר שלהם.", approach: "direct", effects: [{ kind: "set-flag", key: "brom_room_key", value: true }, { kind: "quest-start", questId: "the-wet-ravens-secret" }, { kind: "quest-objective", questId: "the-wet-ravens-secret", objectiveId: "question-brom", status: "completed" }], exitAction: "close" },
      { id: "brom-reassure", text: "אם נמצא משהו, שמך לא יוזכר. אבל מעכשיו אתה מדווח על כל זר.", approach: "kind", effects: [{ kind: "set-flag", key: "brom_room_key", value: true }, { kind: "relationship", npcId: "brom", field: "trust", amount: 5 }, { kind: "quest-start", questId: "the-wet-ravens-secret" }], exitAction: "close" },
    ],
  },
  {
    id: "danor-rescue",
    npcId: "danor",
    portraitKey: "portrait-npc-danor",
    emotionalState: "כאב ופאניקה",
    text: "אל תמשוך סתם—הקורה יושבת על הרגל. הם היו כאן לפנינו. ארבעה עם סמל עין. הם פתחו את הדלת, ומשהו באבן התחיל ללכת.",
    onEnterEffects: [{ kind: "set-flag", key: "danor_found", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "find-trapped-miner", status: "completed" }],
    choices: [
      {
        id: "danor-strength", text: "אני מרים את הקורה. כשאגיד, משוך את הרגל.", approach: "direct",
        skillCheck: {
          skill: "athletics", attribute: "strength", difficulty: 14, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "danor_rescued", value: true }, { kind: "set-flag", key: "danor_resolved", value: true }, { kind: "relationship", npcId: "danor", field: "respect", amount: 8 }],
          failureEffects: [{ kind: "set-flag", key: "danor_condition_worsened", value: true }, { kind: "relationship", npcId: "danor", field: "fear", amount: 5 }],
          criticalSuccessEffects: [{ kind: "set-flag", key: "danor_can_walk", value: true }, { kind: "experience", amount: 35 }],
        },
        nextNodeId: "danor-evidence",
      },
      {
        id: "danor-medicine", text: "אקבע את הרגל ואחליק אותה החוצה בלי להרים את כל המשקל.", approach: "kind",
        skillCheck: {
          skill: "medicine", attribute: "wisdom", difficulty: 12, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "danor_rescued", value: true }, { kind: "set-flag", key: "danor_resolved", value: true }, { kind: "relationship", npcId: "danor", field: "trust", amount: 10 }],
          failureEffects: [{ kind: "set-flag", key: "danor_needs_salve", value: true }],
          criticalSuccessEffects: [{ kind: "set-flag", key: "danor_can_walk", value: true }],
        },
        nextNodeId: "danor-evidence",
      },
      { id: "danor-rope", text: "אעגן את החבל למסילה ואשתמש בה כמנוף.", approach: "curious", conditions: [{ kind: "item", itemId: "soldier-rope", minimumQuantity: 1 }], effects: [{ kind: "set-flag", key: "danor_rescued", value: true }, { kind: "set-flag", key: "danor_resolved", value: true }, { kind: "relationship", npcId: "danor", field: "trust", amount: 7 }], nextNodeId: "danor-evidence" },
      { id: "danor-leave", text: "הדרך קדימה מסוכנת מדי. אשוב אליך אחרי שאעצור את מה שהתעורר.", approach: "direct", effects: [{ kind: "set-flag", key: "danor_left_behind", value: true }, { kind: "set-flag", key: "danor_resolved", value: true }, { kind: "relationship", npcId: "danor", field: "trust", amount: -12 }], exitAction: "close" },
    ],
    oneTime: true,
  },
  {
    id: "danor-evidence",
    npcId: "danor",
    portraitKey: "portrait-npc-danor",
    emotionalState: "מותש אך צלול",
    text: "קח את זה. תלשתי אותו מאחת הגלימות לפני שהמנהרה נפלה. שמעתי אותם אומרים שהרסיס הראשון ‘יקרא לאחרים’.",
    choices: [
      { id: "danor-take-medallion", text: "חזור לכפר דרך הסימונים שלי. אנחנו נסיים את זה.", approach: "kind", effects: [{ kind: "grant-item", itemId: "cult-medallion", quantity: 1 }, { kind: "set-flag", key: "cult_evidence_found", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "discover-prior-intruders", status: "completed" }], exitAction: "close" },
      { id: "danor-question-leader", text: "מי הוביל אותם?", approach: "curious", effects: [{ kind: "set-flag", key: "cult_leader_wore_bone_mask", value: true }, { kind: "grant-item", itemId: "cult-medallion", quantity: 1 }], exitAction: "close" },
    ],
  },
  {
    id: "grey-woman-road",
    npcId: "grey-woman",
    portraitKey: "portrait-npc-grey-woman",
    emotionalState: "בלתי קריאה",
    text: "הם נכנסו כדי למצוא כתר. אתה נכנס כדי למצוא אנשים. השתדל לזכור את ההבדל כשהאבן תציע לך תשובות.",
    choices: [
      { id: "grey-demand-name", text: "מי את, ואיך את יודעת מה יש שם?", approach: "direct", effects: [{ kind: "set-flag", key: "asked_grey_identity", value: true }], nextNodeId: "grey-warning" },
      { id: "grey-ask-shard", text: "איזו אבן מציעה תשובות?", approach: "curious", effects: [{ kind: "set-flag", key: "heard_shard_warning", value: true }], nextNodeId: "grey-warning" },
      { id: "grey-threat", text: "אם את קשורה להיעלמות הכורים, הערפל לא יגן עלייך.", approach: "threatening", effects: [{ kind: "relationship", npcId: "grey-woman", field: "respect", amount: 3 }, { kind: "relationship", npcId: "grey-woman", field: "trust", amount: -3 }], nextNodeId: "grey-warning" },
    ],
    oneTime: true,
  },
  {
    id: "grey-warning",
    npcId: "grey-woman",
    portraitKey: "portrait-npc-grey-woman",
    emotionalState: "עצובה לרגע",
    text: "שבעה שליטים כרעו פעם מפני שלא יכלו להרוג את המלך שמעבר לערפל. הם כבלו אותו בכתר ושברו את הכתר כדי להציל את העולם מעצמם. עכשיו מישהו אוסף את השברים.",
    choices: [
      { id: "grey-who-collects", text: "מי אוסף אותם?", approach: "curious", effects: [{ kind: "set-flag", key: "cult_seeks_crown", value: true }], exitAction: "close" },
      { id: "grey-stop-them", text: "אז אקדים אותם.", approach: "direct", effects: [{ kind: "relationship", npcId: "grey-woman", field: "respect", amount: 4 }], exitAction: "close" },
    ],
  },
  {
    id: "grey-woman-vision",
    npcId: "grey-woman",
    portraitKey: "portrait-npc-grey-woman",
    emotionalState: "קולה נשמע מתוך החזון",
    text: "שבעה שליטים כורעים במעגל. כתר לבן נסגר סביב צל שאין לו גוף. הכתר נשבר לשבעה אורות, והאורות נופלים אל ארצות ואלדר. מעבר לערפל ניצב כס שחור. עין ענקית נפקחת, וקול לוחש: ‘מצאתי אותך.’",
    onEnterEffects: [{ kind: "set-flag", key: "vision_seen", value: true }, { kind: "set-flag", key: "chapter_one_completed", value: true }],
    choices: [
      { id: "vision-resist", text: "לשחרר את הרסיס ולסגת מן הקול.", approach: "direct", effects: [{ kind: "set-flag", key: "resisted_fog_voice", value: true }, { kind: "relationship", npcId: "grey-woman", field: "respect", amount: 5 }], exitAction: "close" },
      { id: "vision-answer", text: "לשאול את הקול: ‘מי אתה?’", approach: "curious", effects: [{ kind: "set-flag", key: "answered_fog_voice", value: true }, { kind: "set-flag", key: "heard_throne_location_hint", value: true }], exitAction: "close" },
      { id: "vision-grip", text: "לאחוז ברסיס ולשמור את החיזיון עד הפרט האחרון.", approach: "direct", effects: [{ kind: "set-flag", key: "memorized_vision", value: true }, { kind: "experience", amount: 80 }], exitAction: "close" },
    ],
    oneTime: true,
  },
];

export const dialoguesById = Object.fromEntries(dialogues.map((dialogue) => [dialogue.id, dialogue])) as Record<string, DialogueNode>;
