import type { Location } from "../types/game";

export const locations: Location[] = [
  {
    id: "village-gate",
    name: "שער הכפר",
    description: "קשת עץ מפוצלת נוטה מעל הדרך. העששיות עדיין מתנדנדות מרעידת האדמה, אף שהאוויר עומד.",
    backgroundAssetKey: "background-village-gate",
    ambienceSoundKey: "ambience-village-wind",
    interactions: [
      {
        id: "inspect-blue-dust",
        label: "בדיקת האבק הכחול",
        description: "אבקה כחולה דקה נחה בסדקי הדרך.",
        skillCheck: {
          skill: "perception", attribute: "wisdom", difficulty: 11, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "blue_dust_found", value: true }],
          failureEffects: [{ kind: "set-flag", key: "strange_tracks_found", value: true }],
          criticalSuccessEffects: [{ kind: "experience", amount: 20 }],
        },
        oneTime: true,
      },
      {
        id: "study-earthquake-cracks",
        label: "בחינת הסדקים",
        description: "הסדקים רחבים ליד השער אך אינם ממשיכים אל הבתים.",
        skillCheck: {
          skill: "investigation", attribute: "intelligence", difficulty: 13, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "quake_was_directed", value: true }],
          failureEffects: [{ kind: "set-flag", key: "quake_uncertain", value: true }],
        },
        oneTime: true,
      },
    ],
    exits: [{ destinationId: "arfelon-square", label: "כניסה לכיכר ערפלון" }],
    npcIds: [],
    lootItemIds: [],
    secretIds: ["blue-dust-origin"],
  },
  {
    id: "arfelon-square",
    name: "כיכר ערפלון",
    description: "תושבים מפנים אבנים מבאר הכפר. מגדל הפעמון סדוק, ובמרכז הקהל אלריק מחלק הוראות בקול שאינו מסגיר פחד.",
    backgroundAssetKey: "background-arfelon-square",
    ambienceSoundKey: "ambience-village-square",
    interactions: [
      { id: "speak-elric-square", label: "שיחה עם אלריק", description: "ראש הכפר מבחין בך ומסמן להתקרב.", dialogueNodeId: "elric-introduction" },
      {
        id: "report-elric-return-rescued",
        label: "דיווח לאלריק ולדנור",
        description: "דנור, חבוש אך עומד, מחכה לצד אלריק. הכיכר כולה שקטה לקראת דבריך.",
        conditions: [{ kind: "flag", key: "vision_seen", value: true }, { kind: "flag", key: "danor_rescued", value: true }],
        dialogueNodeId: "elric-aftermath-rescued",
        oneTime: true,
      },
      {
        id: "report-elric-return-abandoned",
        label: "דיווח על דנור שנותר במכרה",
        description: "אלריק רואה שחזרת לבד. לפני שהוא שואל על הרסיס, הוא שואל מי עוד נשאר מאחור.",
        conditions: [{ kind: "flag", key: "vision_seen", value: true }, { kind: "flag", key: "danor_left_behind", value: true }],
        dialogueNodeId: "elric-aftermath-abandoned",
        oneTime: true,
      },
      {
        id: "listen-crowd",
        label: "האזנה ללחישות",
        description: "בין רעש האבנים עוברות שמועות על צעקות מן הגבעה.",
        skillCheck: {
          skill: "insight", attribute: "wisdom", difficulty: 10, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "villagers_share_nightmare", value: true }],
          failureEffects: [{ kind: "set-flag", key: "villagers_suspicious", value: true }],
        },
        oneTime: true,
      },
    ],
    exits: [
      { destinationId: "headman-house", label: "בית ראש הכפר" },
      { destinationId: "wet-raven-inn", label: "פונדק העורב הרטוב" },
      { destinationId: "smithy", label: "הנפחייה" },
      { destinationId: "healer-hut", label: "בקתת המרפא" },
      { destinationId: "mine-road", label: "הדרך למכרה", conditions: [{ kind: "flag", key: "quest_accepted", value: true }] },
      { destinationId: "village-gate", label: "שער הכפר" },
    ],
    npcIds: ["elric"],
    lootItemIds: [],
    secretIds: ["shared-nightmare"],
  },
  {
    id: "wet-raven-inn",
    name: "פונדק העורב הרטוב",
    description: "עשן כבול לתקרת הקורות. עורב מגולף מטפטף מעל הדלת, וברום מחייך חיוך גדול מדי אל החדר הכמעט ריק.",
    backgroundAssetKey: "background-wet-raven-inn",
    ambienceSoundKey: "ambience-inn-fire",
    interactions: [
      { id: "speak-brom", label: "שיחה עם ברום", description: "בעל הפונדק כבר מוזג משקה שלא ביקשת.", dialogueNodeId: "brom-rumors" },
      {
        id: "speak-brom-return",
        label: "אזהרת ברום מפני אנשי הכת",
        description: "ברום כבר שמע את הפעמונים. הפעם הוא אינו מחייך.",
        conditions: [{ kind: "flag", key: "vision_seen", value: true }],
        dialogueNodeId: "brom-aftermath",
        oneTime: true,
      },
      {
        id: "search-locked-room",
        label: "חיפוש בחדר הנעול",
        description: "מאחורי הדלת עולה ריח של שעווה חרוכה.",
        conditions: [{ kind: "flag", key: "brom_room_key", value: true }],
        skillCheck: {
          skill: "investigation", attribute: "intelligence", difficulty: 12, proficiency: false,
          successEffects: [
            { kind: "set-flag", key: "cult_symbol_seen", value: true },
            { kind: "grant-item", itemId: "cult-medallion", quantity: 1 },
            { kind: "quest-objective", questId: "the-wet-ravens-secret", objectiveId: "search-guest-room", status: "completed" },
          ],
          failureEffects: [
            { kind: "set-flag", key: "room_searched_noisily", value: true },
            { kind: "set-flag", key: "cult_symbol_seen", value: true },
            { kind: "grant-item", itemId: "cult-medallion", quantity: 1 },
            { kind: "quest-objective", questId: "the-wet-ravens-secret", objectiveId: "search-guest-room", status: "completed" },
          ],
          criticalSuccessEffects: [{ kind: "set-flag", key: "hooded_figures_count_known", value: 4 }],
        },
        oneTime: true,
      },
      { id: "buy-hot-meal", label: "ארוחה חמה", description: "תבשיל שורשים סמיך מחזיר מעט כוח.", effects: [{ kind: "heal", amount: 6 }], oneTime: true },
    ],
    exits: [{ destinationId: "arfelon-square", label: "חזרה לכיכר" }],
    npcIds: ["brom"],
    lootItemIds: ["cult-medallion"],
    secretIds: ["cult-guest-room"],
  },
  {
    id: "smithy",
    name: "הנפחייה",
    description: "הכבשן צובע את האבן בכתום עמוק. כלי מכרה מעוקמים מסודרים על שולחן, כאילו משהו סובב את המתכת בידיים.",
    backgroundAssetKey: "background-smithy",
    ambienceSoundKey: "ambience-smithy",
    interactions: [
      { id: "speak-mira", label: "שיחה עם מירה", description: "מירה מניחה פטיש ומחכה שתגיע לעניין.", dialogueNodeId: "mira-earthquake" },
      {
        id: "speak-mira-return",
        label: "הצגת שרידי השומר למירה",
        description: "מירה מזהה את הנחושת שעל ליבת השומר עוד לפני שהנחת אותה על הסדן.",
        conditions: [{ kind: "flag", key: "vision_seen", value: true }],
        dialogueNodeId: "mira-aftermath",
        oneTime: true,
      },
      {
        id: "inspect-bent-tools",
        label: "בדיקת הכלים המעוקמים",
        description: "אין על המתכת סימני חום או פטיש.",
        skillCheck: {
          skill: "investigation", attribute: "intelligence", difficulty: 12, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "stone_magic_suspected", value: true }, { kind: "set-flag", key: "guardian_rune_suspected", value: true }],
          failureEffects: [{ kind: "set-flag", key: "tools_unexplained", value: true }],
        },
        oneTime: true,
      },
    ],
    exits: [{ destinationId: "arfelon-square", label: "חזרה לכיכר" }],
    npcIds: ["mira"],
    lootItemIds: ["miners-pick"],
    secretIds: ["miras-father-hammer"],
  },
  {
    id: "healer-hut",
    name: "בקתת המרפא",
    description: "צרורות עשבים מתייבשים מעל מיטות עמוסות. בין ריחות המרווה והדם מסתתר ריח מתכתי, קר וזר.",
    backgroundAssetKey: "background-healer-hut",
    ambienceSoundKey: "ambience-healer-hut",
    interactions: [
      { id: "speak-thal", label: "שיחה עם תאל", description: "המרפא שוטף אבקה שחורה מידיו לפני שהוא פונה אליך.", dialogueNodeId: "thal-corruption" },
      {
        id: "speak-thal-return",
        label: "בדיקת השפעת הרסיס",
        description: "תאל הכין קערת כסף ומלח עוד לפני ששבת מן המכרה.",
        conditions: [{ kind: "flag", key: "vision_seen", value: true }],
        dialogueNodeId: "thal-aftermath",
        oneTime: true,
      },
      {
        id: "inspect-black-stain",
        label: "בחינת הכתם השחור",
        description: "קו כהה זוחל מתחת לציפורן של תאל.",
        skillCheck: {
          skill: "medicine", attribute: "wisdom", difficulty: 13, proficiency: true,
          successEffects: [{ kind: "set-flag", key: "thal_exposed_to_corruption", value: true }, { kind: "relationship", npcId: "thal", field: "trust", amount: 5 }],
          failureEffects: [{ kind: "set-flag", key: "thal_noticed_stare", value: true }, { kind: "relationship", npcId: "thal", field: "trust", amount: -2 }],
        },
        oneTime: true,
      },
    ],
    exits: [{ destinationId: "arfelon-square", label: "חזרה לכיכר" }],
    npcIds: ["thal"],
    lootItemIds: ["minor-healing-potion", "healers-salve"],
    secretIds: ["thals-corruption"],
  },
  {
    id: "headman-house",
    name: "בית ראש הכפר",
    description: "מפות ישנות מכסות את הקירות. באחת מהן המכרה מסומן בדיו אדומה, אף שהתאריך קדם לסגירתו במאתיים שנה.",
    backgroundAssetKey: "background-headman-house",
    ambienceSoundKey: "ambience-headman-house",
    interactions: [
      { id: "speak-elric-private", label: "שיחה פרטית עם אלריק", description: "מאחורי דלת סגורה קל יותר לשמוע את השקרים.", dialogueNodeId: "elric-quest" },
      {
        id: "show-cult-medallion-elric",
        label: "הצגת מדליון הכת",
        description: "הסמל מן החדר בפונדק תואם לחותם ישן במפה של אלריק.",
        conditions: [{ kind: "item", itemId: "cult-medallion", minimumQuantity: 1 }, { kind: "quest", questId: "the-wet-ravens-secret", status: "active" }],
        dialogueNodeId: "elric-medallion-clue",
        oneTime: true,
      },
      {
        id: "inspect-old-map",
        label: "בחינת המפה הישנה",
        description: "קו דק מוביל מן המכרה אל מעגל אבנים מחוץ לכפר.",
        skillCheck: {
          skill: "investigation", attribute: "intelligence", difficulty: 14, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "old_map_secret_route", value: true }],
          failureEffects: [{ kind: "set-flag", key: "elric_saw_map_search", value: true }, { kind: "relationship", npcId: "elric", field: "trust", amount: -3 }],
        },
        oneTime: true,
      },
    ],
    exits: [{ destinationId: "arfelon-square", label: "חזרה לכיכר" }],
    npcIds: ["elric"],
    lootItemIds: [],
    secretIds: ["elric-ancestral-map"],
  },
  {
    id: "mine-road",
    name: "הדרך למכרה",
    description: "הדרך מטפסת בין אורנים שבורים. הערפל זוחל נגד הרוח, ועל הבוץ נראים עקבים של מגפיים שלא יצאו מן הכפר.",
    backgroundAssetKey: "background-mine-road",
    ambienceSoundKey: "ambience-foggy-road",
    interactions: [
      {
        id: "track-hooded-figures",
        label: "מעקב אחר העקבות",
        description: "ארבעה זוגות מגפיים נעו במבנה מסודר לעבר המכרה.",
        skillCheck: {
          skill: "survival", attribute: "wisdom", difficulty: 12, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "road_ambush_avoided", value: true }, { kind: "set-flag", key: "cult_tracks_found", value: true }],
          failureEffects: [{ kind: "set-flag", key: "road_ambush_triggered", value: true }],
          criticalSuccessEffects: [{ kind: "set-flag", key: "combat_advantage_road", value: true }],
          criticalFailureEffects: [{ kind: "set-flag", key: "surprised_on_road", value: true }],
        },
        encounterId: "road-ambush",
        oneTime: true,
      },
      {
        id: "grey-woman-glimpse",
        label: "הדמות בין העצים",
        description: "גלימה אפורה חולפת במקום שבו הערפל סמיך ביותר.",
        dialogueNodeId: "grey-woman-road",
        conditions: [{ kind: "flag", key: "cult_tracks_found", value: true }],
        oneTime: true,
      },
    ],
    exits: [
      { destinationId: "mine-entrance", label: "המשך אל המכרה", conditions: [{ kind: "flag", key: "interaction_track-hooded-figures_completed", value: true }] },
      { destinationId: "old-watchtower", label: "מגדל התצפית החרב" },
      { destinationId: "standing-stones", label: "מעגל אבני הסף", conditions: [{ kind: "flag", key: "old_map_secret_route", value: true }] },
      { destinationId: "arfelon-square", label: "חזרה לכפר" },
    ],
    npcIds: ["grey-woman"],
    lootItemIds: [],
    secretIds: ["hooded-tracks", "grey-woman-first-appearance"],
  },
  {
    id: "old-watchtower",
    name: "מגדל התצפית החרב",
    description: "המגדל נשען אל הרוח כאדם פצוע. בקומתו העליונה בוערת להבה שחורה שאינה מפיצה חום, ומתחתיה נמתח חבל פעמון חדש מדי בין האבנים העתיקות.",
    backgroundAssetKey: "background-old-watchtower",
    ambienceSoundKey: "ambience-foggy-road",
    interactions: [
      {
        id: "disable-cult-beacon",
        label: "פירוק אות הערפל",
        description: "סביב קערת האש נחרט סדר של שבע נשימות. טעות אחת תזין את הלהבה.",
        skillCheck: {
          skill: "arcana", attribute: "intelligence", difficulty: 13, proficiency: false,
          successEffects: [
            { kind: "set-flag", key: "tower_beacon_disabled", value: true },
            { kind: "set-flag", key: "road_ambush_weakened", value: true },
            { kind: "experience", amount: 45 },
            { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "silence-watchtower", status: "completed" },
          ],
          failureEffects: [
            { kind: "set-flag", key: "tower_beacon_burning", value: true },
            { kind: "set-flag", key: "road_ambush_reinforced", value: true },
            { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "silence-watchtower", status: "failed" },
          ],
          criticalSuccessEffects: [{ kind: "grant-item", itemId: "cult-signal-lens", quantity: 1 }],
        },
        oneTime: true,
      },
      {
        id: "read-watchtower-orders",
        label: "איסוף פקודות הכת",
        description: "דף שעווה מוצמד לקיר בסיכת עצם. השמות נמחקו, אך זמני הכניסה למכרה עדיין קריאים.",
        effects: [
          { kind: "set-flag", key: "cult_orders_recovered", value: true },
          { kind: "set-flag", key: "hooded_figures_count_known", value: 4 },
          { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "discover-prior-intruders", status: "completed" },
          { kind: "experience", amount: 25 },
        ],
        oneTime: true,
      },
      {
        id: "search-watch-post",
        label: "חיפוש בעמדת השומר",
        description: "לוח רצפה אחד נשחק סביב מסמר יחיד, כאילו הוזז שוב ושוב.",
        skillCheck: {
          skill: "perception", attribute: "wisdom", difficulty: 12, proficiency: false,
          successEffects: [{ kind: "grant-item", itemId: "minor-healing-potion", quantity: 1 }, { kind: "set-flag", key: "watchtower_cache_found", value: true }],
          failureEffects: [{ kind: "set-flag", key: "watchtower_cache_missed", value: true }],
        },
        oneTime: true,
      },
    ],
    exits: [{ destinationId: "mine-road", label: "חזרה לדרך למכרה" }],
    npcIds: [],
    lootItemIds: ["cult-signal-lens", "minor-healing-potion"],
    secretIds: ["cult-watch-orders", "fog-beacon"],
  },
  {
    id: "standing-stones",
    name: "מעגל אבני הסף",
    description: "שבע אבנים נמוכות מקיפות תלולית מכוסה עשב. חריצים עתיקים מלאים מי גשם, ורק האבן הפונה למכרה יבשה לחלוטין.",
    backgroundAssetKey: "background-standing-stones",
    ambienceSoundKey: "ambience-village-wind",
    interactions: [
      {
        id: "restore-waystone-oath",
        label: "שחזור שבועת האבנים",
        description: "המפה של אלריק מציגה את סדר המגע, אך המילים נשחקו מן השוליים.",
        skillCheck: {
          skill: "arcana", attribute: "wisdom", difficulty: 14, proficiency: false,
          successEffects: [
            { kind: "set-flag", key: "waystone_ward_restored", value: true },
            { kind: "set-flag", key: "guardian_rune_understood", value: true },
            { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "restore-waystones", status: "completed" },
            { kind: "experience", amount: 60 },
          ],
          failureEffects: [
            { kind: "set-flag", key: "waystone_echo_awakened", value: true },
            { kind: "set-flag", key: "temporary_corruption", value: true },
            { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "restore-waystones", status: "failed" },
          ],
          criticalSuccessEffects: [{ kind: "grant-item", itemId: "waystone-splinter", quantity: 1 }],
        },
        oneTime: true,
      },
      {
        id: "use-elric-seal-at-waystones",
        label: "הנחת מפתח החותם",
        description: "המפתח המשפחתי של אלריק מתאים לשקע באבן הצפונית.",
        conditions: [{ kind: "flag", key: "elric_gave_seal_key", value: true }, { kind: "flag", key: "waystone_echo_awakened", value: true }],
        effects: [
          { kind: "set-flag", key: "waystone_ward_restored", value: true },
          { kind: "set-flag", key: "temporary_corruption", value: false },
          { kind: "heal", amount: 8 },
          { kind: "relationship", npcId: "elric", field: "trust", amount: 3 },
          { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "restore-waystones", status: "completed" },
        ],
        oneTime: true,
      },
      {
        id: "listen-to-waystone",
        label: "הצמדת אוזן לאבן היבשה",
        description: "מתוך הסלע עולה קצב איטי—שלוש פעימות, הפסקה, ואז שבע.",
        effects: [{ kind: "set-flag", key: "seven_three_rhythm_known", value: true }, { kind: "experience", amount: 20 }],
        oneTime: true,
      },
    ],
    exits: [{ destinationId: "mine-road", label: "חזרה לדרך למכרה" }],
    npcIds: [],
    lootItemIds: ["waystone-splinter"],
    secretIds: ["waystone-oath", "seven-three-rhythm"],
  },
  {
    id: "mine-entrance",
    name: "כניסת המכרה",
    description: "קורות התמיכה נבקעו כלפי חוץ. דם יבש נמרח על עגלה הפוכה, וסמל עין שבורה חרוט בפחם על האבן.",
    backgroundAssetKey: "background-mine-entrance",
    ambienceSoundKey: "ambience-mine-mouth",
    interactions: [
      {
        id: "inspect-blood-tools",
        label: "בדיקת הדם והכלים",
        description: "המכוש השבור מוכתם משני צדדיו.",
        skillCheck: {
          skill: "investigation", attribute: "intelligence", difficulty: 11, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "miners_fought_outward", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "find-miner-sign", status: "completed" }],
          failureEffects: [{ kind: "set-flag", key: "blood_trail_missed", value: true }, { kind: "set-flag", key: "miners_sign_found_by_noise", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "find-miner-sign", status: "completed" }],
        },
        oneTime: true,
      },
      {
        id: "inspect-cult-symbol",
        label: "חקירת הסמל",
        description: "עין שבורה שמחציתה נבלעת בשלושה קווי ערפל.",
        skillCheck: {
          skill: "arcana", attribute: "intelligence", difficulty: 14, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "cult_symbol_understood", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "investigate-cult-symbol", status: "completed" }],
          failureEffects: [{ kind: "set-flag", key: "cult_symbol_touched", value: true }, { kind: "set-flag", key: "temporary_corruption", value: true }],
        },
        oneTime: true,
      },
      { id: "tutorial-combat", label: "הרעש מתחת לעגלה", description: "משהו גדול מדי לעכברוש גורר ציפורניים על האבן.", encounterId: "tutorial-rat", oneTime: true },
    ],
    exits: [
      { destinationId: "main-tunnel", label: "כניסה למנהרה הראשית", conditions: [{ kind: "flag", key: "tutorial_enemy_defeated", value: true }] },
      { destinationId: "mine-road", label: "חזרה לדרך" },
    ],
    npcIds: [],
    lootItemIds: ["miners-pick"],
    secretIds: ["miners-fought-something-inside"],
  },
  {
    id: "main-tunnel",
    name: "המנהרה הראשית",
    description: "מסילת העגלות נעלמת מתחת למים שחורים. מן הקיר המזרחי מגיעות שלוש נקישות, הפסקה, ואז קול חלש הקורא לעזרה.",
    backgroundAssetKey: "background-main-tunnel",
    ambienceSoundKey: "ambience-main-tunnel",
    interactions: [
      { id: "listen-danor", label: "הקשבה לקריאה", description: "קולו של אדם מגיע מאחורי מפולת טרייה.", effects: [{ kind: "set-flag", key: "heard_danor", value: true }], oneTime: true },
      {
        id: "find-secret-draft",
        label: "חיפוש מקור הרוח",
        description: "משב קר מזיז אבק במקום שבו הקיר נראה שלם.",
        skillCheck: {
          skill: "perception", attribute: "wisdom", difficulty: 14, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "wall_knocks_heard", value: true }, { kind: "set-flag", key: "secret_passage_marked", value: true }],
          failureEffects: [{ kind: "set-flag", key: "flood_route_only", value: true }],
        },
        oneTime: true,
      },
    ],
    exits: [
      { destinationId: "abandoned-tool-store", label: "מחסן הכלים הנטוש", conditions: [{ kind: "flag", key: "heard_danor", value: true }] },
      { destinationId: "flooded-passage", label: "המעבר המוצף" },
      { destinationId: "mine-entrance", label: "חזרה לכניסה" },
    ],
    npcIds: [],
    lootItemIds: [],
    secretIds: ["three-knock-code", "secret-draft"],
  },
  {
    id: "abandoned-tool-store",
    name: "מחסן הכלים הנטוש",
    description: "מדפים רקובים נשענים זה על זה. מתחת לפעמון אזהרה חלוד, קורה כבדה לוכדת את דנור סמוך ליומן פתוח.",
    backgroundAssetKey: "background-abandoned-tool-store",
    ambienceSoundKey: "ambience-collapsed-chamber",
    interactions: [
      { id: "speak-danor", label: "הרגעת דנור", description: "הכורה נלחם להישאר ער.", dialogueNodeId: "danor-rescue" },
      {
        id: "recover-foreman-journal",
        label: "איסוף היומן",
        description: "העמוד האחרון נכתב בדיו רועדת: ‘הדלת שרה שוב’.",
        effects: [{ kind: "grant-item", itemId: "foreman-journal", quantity: 1 }, { kind: "set-flag", key: "foreman_journal_found", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "find-foreman-journal", status: "completed" }],
        oneTime: true,
      },
      {
        id: "find-rune-hammer",
        label: "פתיחת ארון המנהל",
        description: "מנעול נחושת שונה משאר ציוד המכרה.",
        skillCheck: {
          skill: "investigation", attribute: "intelligence", difficulty: 13, proficiency: false,
          successEffects: [{ kind: "grant-item", itemId: "rune-breaker-hammer", quantity: 1 }, { kind: "set-flag", key: "rune_hammer_found", value: true }],
          failureEffects: [{ kind: "set-flag", key: "cabinet_jammed", value: true }],
        },
        oneTime: true,
      },
    ],
    exits: [{ destinationId: "main-tunnel", label: "חזרה למנהרה" }],
    npcIds: ["danor"],
    lootItemIds: ["foreman-journal", "rune-breaker-hammer", "soldier-rope"],
    secretIds: ["foreman-final-entry", "rune-breaker-weapon"],
  },
  {
    id: "flooded-passage",
    name: "המעבר המוצף",
    description: "מים עד הברכיים משקפים אור כחול שאינו מגיע מן הלפיד. שרשראות גרירה נעות מעצמן מתחת לפני המים.",
    backgroundAssetKey: "background-flooded-passage",
    ambienceSoundKey: "ambience-flooded-passage",
    interactions: [
      {
        id: "cross-flood-safely",
        label: "חציית המים",
        description: "המסילה יוצרת שביל, אך משהו נע משני צדדיה.",
        skillCheck: {
          skill: "acrobatics", attribute: "dexterity", difficulty: 12, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "flood_crossed_quietly", value: true }],
          failureEffects: [{ kind: "set-flag", key: "flood_pack_triggered", value: true }],
        },
        encounterId: "flooded-passage-pack",
        oneTime: true,
      },
      {
        id: "recover-drowned-satchel",
        label: "משיכת התרמיל השקוע",
        description: "רצועת עור נעוצה מתחת למסילה.",
        skillCheck: {
          skill: "athletics", attribute: "strength", difficulty: 11, proficiency: false,
          successEffects: [{ kind: "grant-item", itemId: "minor-healing-potion", quantity: 2 }, { kind: "set-flag", key: "drowned_satchel_found", value: true }],
          failureEffects: [{ kind: "set-flag", key: "made_noise_in_flood", value: true }],
        },
        oneTime: true,
      },
    ],
    exits: [
      { destinationId: "pillar-hall", label: "עלייה אל אולם העמודים", conditions: [{ kind: "flag", key: "flood_pack_defeated", value: true }, { kind: "flag", key: "danor_resolved", value: true }] },
      { destinationId: "main-tunnel", label: "חזרה למנהרה" },
    ],
    npcIds: [],
    lootItemIds: ["minor-healing-potion"],
    secretIds: ["blue-light-below-water"],
  },
  {
    id: "pillar-hall",
    name: "אולם העמודים",
    description: "עמודים שקדמו למכרה נושאים תבליטים של שבע דמויות כורעות. עקבות גלימות מסתיימות מול קיר אטום.",
    backgroundAssetKey: "background-pillar-hall",
    ambienceSoundKey: "ambience-pillar-hall",
    interactions: [
      {
        id: "study-cult-remains",
        label: "חקירת שרידי הטקס",
        description: "שעווה שחורה, כתב שרוף וגביש שנשבר מבפנים.",
        skillCheck: {
          skill: "arcana", attribute: "intelligence", difficulty: 13, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "cult_opened_guardian_hall", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "discover-prior-intruders", status: "completed" }],
          failureEffects: [{ kind: "set-flag", key: "cult_clue_incomplete", value: true }, { kind: "set-flag", key: "guardian_awakened_early", value: true }, { kind: "set-flag", key: "cult_opened_guardian_hall", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "discover-prior-intruders", status: "completed" }],
          criticalSuccessEffects: [{ kind: "set-flag", key: "guardian_rune_understood", value: true }],
        },
        oneTime: true,
      },
      {
        id: "open-hidden-door",
        label: "פתיחת המעבר הנסתר",
        description: "שלוש נקישות על האבן, הפסקה, ונקישה רביעית.",
        conditions: [{ kind: "flag", key: "secret_passage_marked", value: true }],
        effects: [{ kind: "set-flag", key: "hidden_chamber_open", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "discover-secret-passage", status: "completed" }],
        oneTime: true,
      },
    ],
    exits: [
      { destinationId: "hidden-chamber", label: "החדר הנסתר", conditions: [{ kind: "flag", key: "hidden_chamber_open", value: true }] },
      { destinationId: "guardian-sanctum", label: "היכל השומר", conditions: [{ kind: "flag", key: "cult_opened_guardian_hall", value: true }] },
      { destinationId: "flooded-passage", label: "חזרה למעבר המוצף" },
    ],
    npcIds: [],
    lootItemIds: ["black-crystal"],
    secretIds: ["seven-kneeling-rulers", "cult-burned-instruction"],
  },
  {
    id: "hidden-chamber",
    name: "החדר הנסתר",
    description: "החדר עגול ויבש. מפה של שבעה אזורים חרוטה ברצפה, ובמרכזה תיבה שלא נגע בה אבק אלף שנים.",
    backgroundAssetKey: "background-hidden-chamber",
    ambienceSoundKey: "ambience-hidden-chamber",
    interactions: [
      {
        id: "decode-seven-regions",
        label: "פענוח מפת שבעת האזורים",
        description: "כל אזור מחובר לאחר בקו שמקיף חלל ריק במרכז.",
        skillCheck: {
          skill: "arcana", attribute: "intelligence", difficulty: 15, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "seven_shards_lore", value: true }, { kind: "set-flag", key: "guardian_rune_understood", value: true }, { kind: "experience", amount: 60 }],
          failureEffects: [{ kind: "set-flag", key: "map_remembered", value: true }],
        },
        oneTime: true,
      },
      {
        id: "open-ancient-chest",
        label: "פתיחת התיבה העתיקה",
        description: "המנעול מעוצב כשבע אצבעות האוחזות זו בזו.",
        effects: [{ kind: "grant-item", itemId: "fogglass-ring", quantity: 1 }, { kind: "set-flag", key: "hidden_loot_claimed", value: true }],
        oneTime: true,
      },
    ],
    exits: [{ destinationId: "pillar-hall", label: "חזרה לאולם העמודים" }],
    npcIds: [],
    lootItemIds: ["fogglass-ring"],
    secretIds: ["seven-shard-map", "guardian-weakness-lore"],
  },
  {
    id: "guardian-sanctum",
    name: "היכל השומר",
    description: "אולם בזלת אדיר נפתח אל תהום. פסל כבול ניצב לפני כן אבן, וברונה שבחזהו נדלק אור כחול כשנעשית הצעד הראשון.",
    backgroundAssetKey: "background-guardian-sanctum",
    ambienceSoundKey: "ambience-guardian-sanctum",
    interactions: [
      {
        id: "inspect-guardian-before-combat",
        label: "בחינת השומר",
        description: "הרונה בחזה מחוברת לשרשראות, לא לגוף האבן.",
        skillCheck: {
          skill: "investigation", attribute: "intelligence", difficulty: 14, proficiency: false,
          successEffects: [{ kind: "set-flag", key: "guardian_rune_understood", value: true }],
          failureEffects: [{ kind: "set-flag", key: "guardian_awakened_early", value: true }],
        },
        oneTime: true,
      },
      { id: "fight-stone-guardian", label: "התמודדות עם השומר", description: "השרשראות נקרעות בזו אחר זו.", encounterId: "stone-guardian-boss", oneTime: true },
      {
        id: "touch-first-shard",
        label: "נגיעה ברסיס",
        description: "המתכת מרחפת מעל כן האבן ומשקפת עין ענקית מאחורי ערפל.",
        conditions: [{ kind: "flag", key: "guardian_defeated", value: true }],
        effects: [{ kind: "grant-item", itemId: "first-crown-shard", quantity: 1 }, { kind: "set-flag", key: "shard_touched", value: true }, { kind: "quest-objective", questId: "shadows-beneath-village", objectiveId: "inspect-shard", status: "completed" }],
        dialogueNodeId: "grey-woman-vision",
        oneTime: true,
      },
    ],
    exits: [
      { destinationId: "arfelon-square", label: "חזרה לערפלון דרך נתיב דנור", conditions: [{ kind: "flag", key: "vision_seen", value: true }] },
      { destinationId: "pillar-hall", label: "חזרה לאולם העמודים" },
    ],
    npcIds: ["grey-woman"],
    lootItemIds: ["first-crown-shard", "guardian-core"],
    secretIds: ["first-crown-shard", "voice-beyond-fog"],
  },
];

export const locationsById = Object.fromEntries(locations.map((location) => [location.id, location])) as Record<string, Location>;
